/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class FourPointDelayAudioProcessorEditor  : public AudioProcessorEditor,
                                            Slider::Listener,
                                            Button::Listener,
                                            Timer
{
public:
    FourPointDelayAudioProcessorEditor (FourPointDelayAudioProcessor&);
    ~FourPointDelayAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    
    void timerCallback();
    void sliderValueChanged (Slider* sliderThatWasChanged);
    
    void buttonClicked(Button* button);

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    FourPointDelayAudioProcessor& processor;
    
    ScopedPointer<Slider> knob1;
    ScopedPointer<Slider> knob2;
    ScopedPointer<Slider> knob3;
    
    TextButton button1;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (FourPointDelayAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
